---
- name: Install Docker on remote host
  hosts: all
  become: true
  roles:
    - roles/common

- name: Create a Docker network
  hosts: all
  become: yes
  tasks:
    - name: Create Docker network
      docker_network:
        name: my-network
        state: present

- name: Run mongodb
  hosts: db
  become: true
  roles:
    - roles/db

- name: Run webapp
  hosts: 
    - web_app_1
    - web_app_2
  become: true
  roles:
    - roles/api

- name: Run nginx front-end
  hosts: web_app_1, web_app_2
  become: true
  roles:
    - roles/web

- name: nginx load balancer
  hosts: nginx_lb
  become: true
  roles:
    - roles/load-balancer