- name: Pull Nginx-lb image
  community.general.docker_image:
    name: leqa/lqa-load-balancer
    tag: latest
    source: pull
    state: present
    force_source: true

- name: Run Nginx-lb
  docker_container:
    name: nginx_test
    image: leqa/lqa-load-balancer:latest
    state: started
    restart_policy: unless-stopped
    ports:
      - 80:80
    network_mode: my-network