- name: Pull Flask image
  community.general.docker_image:
    name: leqa/lqa-flask-app
    tag: latest
    source: pull
    state: present
    force_source: true

- name: Run Flask container
  community.docker.docker_container:
    name: flask_container
    image: leqa/lqa-flask-app:latest
    command: python init.py
    restart_policy: unless-stopped
    env:
      COLOR: "{{COLOR}}"
    ports:
      - "5000:5000"
    network_mode: my-network





