- name: Run Nginx
  docker_container:
    name: nginx_test
    image: leqa/lqa-web:latest
    state: started
    restart_policy: unless-stopped
    ports:
      - 80:80
    networks: 
      - name: my-network